views/answer_view.py
from flask import Blueprint, request, url_for, render_template, g, flash
from werkzeug.utils import redirect

from jump2 import db
from jump2.models import Question, Answer
from jump2.forms import AnswerForm
from jump2.views.auth_view import login_required

from datetime import datetime

# markdown and markdown to text
import markdown
# from jump2.markdownfile import html2text

bp = Blueprint('answer', __name__, url_prefix = '/answer')

@bp.route('/create/<int:question_id>', methods = ('POST',))
@login_required
def create(question_id) : 
    
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit() :
        ## update real answer in Answer tables
        content = request.form['content']
        answer = Answer(content=content, create_date = datetime.now(), user=g.user)
        ## backref
        question.answer_set.append(answer)
        db.session.commit()
        
        #return redirect(url_for('question.detail', question_id=question_id))
        # redirect to anchor 
        return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=question_id), answer.id))
    
    ## question : question_view blueprint, detail : routing func
    return render_template('question/question_detail.html', question=question, form=form)

# modify answer content endpoint
@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id) : 
    
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user : 
        flash('do not have modification permissions.')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == 'POST' : 
        form = AnswerForm()
        if form.validate_on_submit() :
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            
            #return redirect(url_for('question.detail', question_id=answer.question.id))
            # redirect to anchor
            return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=answer.question.id), answer.id))
    else :
        form = AnswerForm(obj=answer)
        return render_template('answer/answer_form.html', form=form, answer=answer)
    
# delete answer content endpoint
@bp.route('/delete/<int:answer_id>')    
@login_required
def delete(answer_id) :
    
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user :
        flash('do not have modification permissions.')
    else :
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

@bp.route('/vote/<int:answer_id>')
@login_required
def vote(answer_id) : 
    
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user : 
        flash('this is your content do not recommend')
    else :
        _answer.voter.append(g.user)
        db.session.commit()
        
    ## _answer.question : relationship column about backref
    #return redirect(url_for('question.detail', question_id=_answer.question.id))
    # redirect to anchor
    return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=_answer.question.id), _answer.id))

templates/answer/answer_form.html
<!-- form : modify answer content -->
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">modify answer</h5>
    <form method="post">
        {{form.csrf_token}}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content">content</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{form.content.data or ''}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">send</button>
        <a href="{{url_for('answer.delete', answer_id=answer.id)}}" class="btn btn-primary">delete</a>
    </form>
</div>
{% endblock %}

templates/answer/answer_list_v1.html
<!-- answer list v1-->
<h3 class="my-3 border-bottom pb-2">Answer list : {{question.answer_set | length}} answers</h3>
    <div class="card my-3">
        <div class="card-body">
            {% for answer in question.answer_set %}
            <!-- anchor -->
            <a id="answer_{{answer.id}}"></a>
            <!-- apply a markdown func -->
            <div class="card-text">{{answer.content | safe}}</div>
            <!-- time : modify and create -->    
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{answer.modify_date | datetime}}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{answer.user.username}}</div>
                    <div>{{answer.create_date | datetime}}</div>
                </div>
            </div>
            <!-- button : recommend, modify, delete -->
            <div class="my-3">
                <!-- recommend : open pop up window and count number badge -->
                <a href="javascript:void(0)" data-uri="{{url_for('answer.vote', answer_id=answer.id)}}"
                    class="recommend btn btn-sm btn-outline-secondary">recommend
                <span class="badge rounded-pill bg-success">{{answer.voter | length}}</span>
                </a>
                {% if g.user == answer.user %}
                <a href="{{url_for('answer.modify', answer_id=answer.id)}}"
                    class="btn btn-sm btn-outline-secondary">modify</a>
                <!-- delete : open pop up window -->    
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{{url_for('answer.delete', answer_id=answer.id)}}">delete</a>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div> 

templates/answer/answer_list_v2.html
<!-- answer list v2 -->
{% block content %}
<div class="container my-3">
    <h3 class="my-3 border-bottom pb-2">Answer list : {{question.answer_set | length}} answers</h3>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>number</th>
            <th style="width:40%">answer</th>
            <th style="width:10%">like</th>
            <th>username</th>
            <th>date</th>
            <th>modify date</th>
        </tr>
        </thead>
        <tbody>
            {% if answer_list %}
            {% for answer in answer_list.items %}
            <a id="answer_{{answer.id}}"></a>
            <tr class="text-center">
                <!-- answer contents number -->
                <td>{{answer_list.total - ((answer_list.page - 1) * answer_list.per_page) - loop.index0}}</td>
                <!-- answer contents -->
                <td class="text-center"> 
                    <a href="{{url_for('answer.modify', answer_id=answer.id)}}">{{answer.content | safe}}</a>
                </td>
                <!-- like -->
                <td>
                    <a href="javascript:void(0)" data-uri="{{url_for('answer.vote', answer_id=answer.id)}}"
                        class="recommend btn btn-sm btn-outline-secondary">like
                    <span class="badge rounded-pill bg-success">{{answer.voter | length}}</span>
                    </a>
                </td>
                <!-- user name -->
                <td>{{answer.user.username}}</td>
                <!-- create date -->
                <td>{{answer.create_date | datetime}}</td>
                <!-- modify date -->
                {% if answer.modify_date %}
                    <td>{{answer.modify_date | datetime}}</td>
                {% else %}
                    <td>{{answer.modify_date}}</td>
                {% endif %}
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">not answer.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!--paging button bar-->
    <ul class="pagination justify-content-center">
        <!-- butoon : before -->
        {% if answer_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{answer_list.prev_num}}">before</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">before</a>
        </li>
        {% endif %}
        <!-- button : current page number -->
        {% for page_num in answer_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != answer_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_num}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{page_num}}</a>
        </li>
        {% endif %}
        <!-- button : more pages -->
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- button : next -->
        {% if answer_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{answer_list.next_num}}">next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">next</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}