views/answer_view.py
from flask import Blueprint, request, url_for, render_template, g, flash
from werkzeug.utils import redirect

from jump2 import db
from jump2.models import Question, Answer
from jump2.forms import AnswerForm
from jump2.views.auth_view import login_required

from datetime import datetime

# markdown and markdown to text
import markdown
# from jump2.markdownfile import html2text

bp = Blueprint('answer', __name__, url_prefix = '/answer')

@bp.route('/create/<int:question_id>', methods = ('POST',))
@login_required
def create(question_id) : 
    
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit() :
        ## update real answer in Answer tables
        content = request.form['content']
        answer = Answer(content=content, create_date = datetime.now(), user=g.user)
        ## backref
        question.answer_set.append(answer)
        db.session.commit()
        
        #return redirect(url_for('question.detail', question_id=question_id))
        # redirect to anchor 
        return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=question_id), answer.id))
    
    ## question : question_view blueprint, detail : routing func
    return render_template('question/question_detail.html', question=question, form=form)

# modify answer content endpoint
@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id) : 
    
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user : 
        flash('do not have modification permissions.')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == 'POST' : 
        form = AnswerForm()
        if form.validate_on_submit() :
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            
            #return redirect(url_for('question.detail', question_id=answer.question.id))
            # redirect to anchor
            return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=answer.question.id), answer.id))
    else :
        form = AnswerForm(obj=answer)
        return render_template('answer/answer_form.html', form=form, answer=answer)
    
# delete answer content endpoint
@bp.route('/delete/<int:answer_id>')    
@login_required
def delete(answer_id) :
    
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user :
        flash('do not have modification permissions.')
    else :
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

@bp.route('/vote/<int:answer_id>')
@login_required
def vote(answer_id) : 
    
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user : 
        flash('this is your content do not recommend')
    else :
        _answer.voter.append(g.user)
        db.session.commit()
        
    ## _answer.question : relationship column about backref
    #return redirect(url_for('question.detail', question_id=_answer.question.id))
    # redirect to anchor
    return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=_answer.question.id), _answer.id))

views/question_view.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from jump2 import db
from jump2.models import Question, Answer, User, answer_voter as av
# QuestionForm class in forms.py
from jump2.forms import QuestionForm, AnswerForm
from jump2.views.auth_view import login_required

from sqlalchemy import func

from datetime import datetime

# markdown, markdown to text
import markdown
# from jump2.markdownfile import html2text

bp = Blueprint('question', __name__, url_prefix='/question')

"""
origin question list endpoint, change code

@bp.route('/list/')
def qlist() :
    
    # get page values in GET request : localhost:5000/question/list/?page=num
    page = request.args.get('page', type=int, default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    # paginate func : auto paging
    question_list = question_list.paginate(page=page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list)
"""
# question list new code with search func
@bp.route('/list/', methods=('GET', 'POST'))
def qlist() :
    
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    question_list = Question.query.order_by(Question.create_date.desc())
    
    if kw :
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username)\
                .join(User, Answer.user_id == User.id).subquery()
        question_list = question_list\
                .join(User)\
                .outerjoin(sub_query, sub_query.c.question_id == Question.id)\
                .filter(Question.subject.ilike(search) |
                        Question.content.ilike(search) |
                        User.username.ilike(search) |
                        sub_query.c.content.ilike(search) |
                        sub_query.c.username.ilike(search))\
                .distinct()
    
    question_list = question_list.paginate(page=page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)

@bp.route('/detail/<int:question_id>/', methods=['GET', 'POST'])
def detail(question_id) : 
    
    answer_form = AnswerForm()
    # 404 error return 
    ## Question.query.get(question_id) ---> Question.query.get_or_404(question_id)
    question = Question.query.get_or_404(question_id)
    
    
    # markdown question content
    question.content = markdown.markdown(question.content, extentions=['nl2br', 'fenced_code'])
    # markdown answer content
    if question.answer_set : 
        for i, answer in enumerate(question.answer_set) :
            question.answer_set[i].content = markdown.markdown(answer.content, extentions=[['nl2br', 'fenced_code']])
    
    # pagenation for answer_list.html
    page = request.args.get('page', type=int, default=1)
    # sort by count answer_voter, av : import answer_voter table
    sub_query = db.session.query(av.c.answer_id, func.count(av.c.user_id).label('count')) \
                          .group_by(av.c.answer_id).subquery()
    answer_list = Answer.query.filter(Answer.question_id == question_id)
    answer_list = answer_list.outerjoin(sub_query, sub_query.c.answer_id == Answer.id).order_by(sub_query.c.count.desc())
    answer_list = answer_list.paginate(page=page, per_page=3)
    
    # answer_list = Answer.query.order_by(Answer.create_date.desc()).filter(Answer.question_id == question_id)
    
    return render_template('question/question_detail.html', question=question, answer_form=answer_form, answer_list=answer_list)

@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create() : 
    
    form = QuestionForm()
    
    # input data insert into db
    if request.method == 'POST' and form.validate_on_submit() :
        question = Question(subject=form.subject.data, content=form.content.data, 
                            create_date = datetime.now(), user=g.user)
        
        db.session.add(question)
        db.session.commit()
        # main : main.view blueprint, index : routing func
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

# modify question endpoint
@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id) :
     
    question = Question.query.get_or_404(question_id)
    
    ## g.user : login user, question.user : create question user
    if g.user != question.user : 
        flash('do not have modification permissions.')
        return redirect(url_for('question.detail', question_id=question_id))
    
    ## if modify save button : POST
    if request.method == 'POST' : 
        form = QuestionForm()
        
        if form.validate_on_submit() :
            ## update to question obj with modified content now
            form.populate_obj(question)
            ## modify datetime save
            question.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    
    ## if modify button request : GET
    else :
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)

# delete question endpoint
@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id) : 
    
    question = Question.query.get_or_404(question_id)
    
    if g.user != question.user :
        flash('do not have modification permissions.')
        return redirect(url_for('question.detail', question_id=question_id))
    
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question.qlist'))

@bp.route('/vote/<int:question_id>')
@login_required
def vote(question_id) : 
    
    _question = Question.query.get_or_404(question_id)
    
    if g.user == _question.user :
        flash('this is your content do not recommend')
        
    else :
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

templates/question/question_detail.html
<!-- question detail page -->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- flash error -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{message}}
    </div>
    {% endfor %}
    <!-- question content -->
    <h3 class="my-3 border-bottom pb-2">Q : {{question.subject}}</h3>
    <div class="card my-3">
        <div class="card-body">
            <!-- apply a markdown func -->
            <div class="card-text">{{question.content | safe}}</div>
            <!-- time : modify and create -->
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{question.modify_date | datetime}}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{question.user.username}}</div>
                    <div>{{question.create_date | datetime}}</div>
                </div>
            </div>
            <!-- button : recommend, modify, delete -->
            <div class="my-3">
                <!-- recommend : open pop up window and count number badge -->
                <a href="javascript:void(0)" data-uri="{{url_for('question.vote', question_id=question.id)}}"
                  class="recommend btn btn-sm btn-outline-secondary">like
                  <span class="badge rounded-pill bg-success">{{question.voter | length}}</span>
                </a>
                {% if g.user == question.user %}
                <a href="{{url_for('question.modify', question_id=question.id)}}" 
                   class="btn btn-sm btn-outline-secondary">modify</a>
                <!-- delete : open pop up window -->   
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary" 
                   data-uri="{{url_for('question.delete', question_id=question.id)}}">delete</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- answer content create -->
    <h3 class="my-3 border-bottom pb-2">A : Insert your answer.</h3>
    <form action="{{url_for('answer.create', question_id=question.id)}}" method="post" class="my-3">
        <!-- csrf token -->
        {{answer_form.csrf_token}}
        <!-- form : errors -->
        {% if answer_form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in answer_form.errors.items() %}
            <strong>{{answer_form[field].label}}</strong>
            <ul>
                {% for error in errors %}
                <li>{{error}}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <div class="mb-3">
            <!-- if do not log, field is disabled -->
            <textarea 
            {% if not g.user %}
            disabled
            {% endif %}
            name="content" id="content" class="form-control" rows="10"></textarea>
        </div>    
        <button type="submit" class="btn btn-primary">send</button>
    </form>
    <!-- answer list content -->
    {% include 'answer/answer_list_v2.html'%}
</div>
{% endblock %}
<!-- javascript func for open pop up window -->
{% block script %}
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete") ;
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("really delete?")) {
                location.href = this.dataset.uri ;
        };
    });
});
    const recommend_elements = document.getElementsByClassName("recommend") ; 
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("really recommend?")) {
                location.href=this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/question/question_form.html
<!-- form : question content / link 'Insert Question' -->
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h3 class="my-3 border-bottom pb-2">What is your Question?</h3>
    <form method="post" class="my-3">
        <!-- csrf token create -->
        {{form.csrf_token}}
        <!-- form : form errors -->
        {% include "form_errors.html"%}
        <!-- content : title and field -->
        <div class="mb-3">
            <label for="subject">title</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{form.subject.data or ''}}">
        </div>
        <!-- content : title and field -->
        <div class="mb-3">
            <label for="content">content</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{form.content.data or ''}}</textarea>
        </div>
        <!-- button : send -->
        <button type="submit" class="btn btn-primary">send</button>
    </form>
</div> 
{% endblock %}

templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">   
   <!-- insert question and search bar -->
   <div class="row my-3">
      <!-- insert question -->
      <div class="col-6">
         <a href="{{url_for('question.create')}}" class="btn btn-primary">Insert Question</a>
      </div>
      <!-- search bar -->
      <div class="col-6">
         <div class="input-group">
            <input type="text" id="search_kw" class="form-control" value="{{ kw or ''}}">
            <div class="input-group-append">
               <button class="btn btn-outline-secondary" type="button" id="btn_search">search</button>
            </div>
         </div>
      </div>
   </div>
   <!-- question list table -->
   <table class="table">
      <thead>
      <tr class="text-center table-dark">
         <th>number</th>
         <th style="width:50%">title</th>
         <th>username</th>
         <th>date</th>
      </tr>
      </thead>
      <tbody>
      {% if question_list %}
      {% for question in question_list.items %}
      <tr class="text-center">
         <!-- question content numbering -->
         <td>{{question_list.total - ((question_list.page - 1) * question_list.per_page) - loop.index0}}</td>
         <td class="text-start">
            <!-- question content title -->
            <a href="{{url_for('question.detail', question_id=question.id)}}">{{question.subject}}</a>
            <!-- answer count number badge -->
            {% if question.answer_set | length > 0%}
            <span class="text-danger small mx-2">[{{question.answer_set | length}}]</span>
            {% endif %}
         </td>
         <!-- question content user name -->
         <td>{{question.user.username}}</td>
         <!-- question content create date -->
         <td>{{question.create_date | datetime}}</td>
      </tr>
      {% endfor %}
      <!-- empty question content -->
      {% else %}
      <tr>
         <td colspan="4">not question.</td>
      </tr>
      {% endif %}
      </tbody>
   </table>
   <!-- pasing button bar -->
   <ul class="pagination justify-content-center">
      <!-- button : before -->
      {% if question_list.has_prev %}
      <li class="page-item">
         <a class="page-link" data-page="{{question_list.prev_num}}" href="javascript:void(0)">before</a>
      </li>
      {% else %}
      <li class="page-item disabled">
         <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">before</a>
      </li>
      {% endif %}
      <!-- button : current page number -->
      {% for page_num in question_list.iter_pages() %}
      {% if page_num %}
      {% if page_num != question_list.page %}
      <li class="page-item">
         <a class="page-link" data-page="{{page_num}}" href="javascript:void(0)">{{page_num}}</a>
      </li>
      {% else %}
      <li class="page-item active" aria-current="page">
         <a class="page-link" href="#">{{page_num}}</a>
      </li>
      {% endif %}
      <!-- button : more pages -->
      {% else %}
      <li class="disabled">
         <a class="page-link" href="javascript:void(0)">...</a>
      </li>
      {% endif %}
      {% endfor %}
      <!-- button : next -->
      {% if question_list.has_next %}
      <li class="page-item">
         <a class="page-link" data-page="{{question_list.next_num}}" href="javascript:void(0)">next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
         <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">next</a>
      </li>
      {% endif %}
   </ul>
</div>
<!-- form : search keyword and page -->
<form id="searchForm" method="get" action="{{url_for('question.qlist')}}">
   <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
   <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
<!-- search func javascript -->
{% block script %}
<script type='text/javascript'>
   const page_elements = document.getElementsByClassName("page-link") ;
   Array.from(page_elements).forEach(function(element) {
      element.addEventListener('click', function() {
         document.getElementById('page').value = this.dataset.page ;
         document.getElementById('searchForm').submit() ;
   }) ;
}) ;
   const btn_search = document.getElementById("btn_search") ;
   btn_search.addEventListener('click', function() {
         document.getElementById('kw').value = document.getElementById('search_kw').value ;
         document.getElementById('page').value = 1 ;
         document.getElementById('searchForm').submit() ; 
}) ;
</script>
{% endblock%}